### ISSUE TITLE
JWT Strategy?

### ISSUE THREAD

**Issue by jamshally** [artonio/nestjs-session-tutorial-finished#1]
Thank you for taking the time to share this code, and your [blog post](http://blog.exceptionfound.com/index.php/2018/06/07/nestjs-basic-auth-and-sessions/) - it has been very useful for me, especially around the nest authentication code, which I have been wrestling with for a while.

I have a question.  Posting here on github because the blog engine was blocking me as a 'suspected bot'... not sure why :-/ 

**Question**
Did you consider a JWT passport strategy instead of a customer passport strategy?  And if so, why did you go with the custom?

Thanks

**Comment by artonio** [comment]
Hey, I'm glad you found this useful. As to your question, no particular
reason, there are a lot of JWT tutorials, wanted to do something different.
Ultimately it is up to the developer to choose the best auth strategy that
suit their project.

I have forked and made a pull request at Awesome Nest where I added the
article but it has not been merged nor reviewed yet.

Cheers
